# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-25 14:23
from __future__ import unicode_literals

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import typeidea.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatar/default/avatar.png', storage=typeidea.storage.OverwriteStorage(), upload_to=account.models.user_avatar_path, verbose_name='\u5934\u50cf')),
                ('location', models.IntegerField(choices=[(0, '\u4fdd\u5bc6'), (1, '\u5317\u4eac\u5e02'), (2, '\u5929\u6d25\u5e02'), (3, '\u4e0a\u6d77\u5e02'), (4, '\u91cd\u5e86\u5e02'), (5, '\u6cb3\u5317\u7701'), (6, '\u5c71\u897f\u7701'), (7, '\u8fbd\u5b81\u7701'), (8, '\u5409\u6797\u7701'), (9, '\u9ed1\u9f99\u6c5f\u7701'), (10, '\u6c5f\u82cf\u7701'), (11, '\u6d59\u6c5f\u7701'), (12, '\u5b89\u5fbd\u7701'), (13, '\u798f\u5efa\u7701'), (14, '\u6c5f\u897f\u7701'), (15, '\u5c71\u4e1c\u7701'), (16, '\u6cb3\u5357\u7701'), (17, '\u6e56\u5317\u7701'), (18, '\u6e56\u5357\u7701'), (19, '\u5e7f\u5dde\u7701'), (20, '\u6d77\u5357\u7701'), (21, '\u56db\u5ddd\u7701'), (22, '\u8d35\u5dde\u7701'), (23, '\u4e91\u5357\u7701'), (24, '\u9655\u897f\u7701'), (25, '\u7518\u8083\u7701'), (26, '\u9752\u6d77\u7701'), (27, '\u53f0\u6e7e\u7701'), (28, '\u5185\u8499\u53e4\u81ea\u6cbb\u533a'), (29, '\u5e7f\u897f\u58ee\u65cf\u81ea\u6cbb\u533a'), (30, '\u897f\u85cf\u81ea\u6cbb\u533a'), (31, '\u5b81\u590f\u56de\u65cf\u81ea\u6cbb\u533a'), (32, '\u65b0\u7586\u7ef4\u543e\u5c14\u81ea\u6cbb\u533a'), (33, '\u9999\u6e2f\u7279\u522b\u884c\u653f\u533a'), (34, '\u6fb3\u95e8\u7279\u522b\u884c\u653f\u533a')], default=0, verbose_name='\u4f4d\u7f6e')),
                ('blog_site', models.URLField(blank=True, max_length=30, verbose_name='\u535a\u5ba2\u5730\u5740')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
    ]
