# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180117_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html',
            field=models.TextField(help_text='markdown\u683c\u5f0f\u7684\u5185\u5bb9\u7ecf\u8fc7\u8f6c\u6362\u6210\u4e3ahtml\u5185\u5bb9', null=True, verbose_name='html\u5185\u5bb9'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_markdown',
            field=models.BooleanField(default=True, verbose_name='\u4f7f\u7528markdown\u683c\u5f0f'),
        ),
    ]
