# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180118_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pv',
            field=models.IntegerField(default=0),
        ),
    ]
