# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-11 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180122_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='\u6ce8\uff1a\u4f7f\u7528markdown\u6a21\u5f0f\u65f6\u4f7f\u7528\u6e90\u7801\u8fdb\u884c\u7f16\u8bd1', verbose_name='\u5185\u5bb9'),
        ),
    ]
